### ISSUE TITLE
RFE: demangle by whitespace, not just lines

### ISSUE THREAD

**Issue by cuviper** [luser/rustfilt#1]
A lot of times when I want to demangle, the symbols aren't alone on a line.  e.g. `nm` output like:

```
0000000000004110 t _ZN8rustfilt12try_demangle17h684bf4347fc3e268E
0000000000004410 t _ZN8rustfilt4main17h9b49b8def9105b7bE
```

Piping that through `rustfilt` does nothing, but `c++filt` gives:

```
0000000000004110 t rustfilt::try_demangle::h684bf4347fc3e268
0000000000004410 t rustfilt::main::h9b49b8def9105b7b
```

Of course, `c++filt` doesn't handle more-complicated Rust mangling, so I'd like `rustfilt` to work. :)

**Comment by luser** [comment]
Ideally rustfilt would operate like c++filt! I don't have a particular need for this currently, but I'd be happy to take a patch.
