### ISSUE TITLE
Can't demangle _ZN3std9panicking12de​fault_hook17hf6fdb8e9​192be332E

### ISSUE THREAD

**Issue by glandium** [luser/rustfilt#8]
```
$ rustfilt _ZN3std9panicking12default_hook17f6fdb8e9​192be332E
3std9panicking12default_hook17f6fdb8e9​192be332
```

Incidentally, c++filt can't demangle it either:
```
$ c++filt _ZN3std9panicking12de​fault_hook17hf6fdb8e9​192be332E
_ZN3std9panicking12de​fault_hook17hf6fdb8e9​192be332E
```

But rustfilt's output is removing some parts, which it probably shouldn't. I don't know the inner details of mangling format that make this not work. All I know is the trivial <number><number-of-chars> thing, that E is for the end, and that other letters can be used to indicate template arguments, function arguments, etc., but it doesn't look like any of those is involved.

Cc: @alexcrichton

**Comment by alexcrichton** [comment]
Hm where'd the symbol come from? If I copy/paste from GitHub here it has what looks like a zero-width space in the middle:

```
"_ZN3std9panicking12default_hook17f6fdb8e9\u{200b}192be332E"
```

additionally the hash at the end of rust symbols typically starts with an `h` but the symbol there ends with `17f6f...` where it should be `17f6f...`. It's probably a bug that rustc-demangle chops off the `_ZN3` and the `E` though

**Comment by glandium** [comment]
Dammit, it's a copy/paste problem from diffoscope. Sorry for the noise.

```
$ c++filt _ZN3std9panicking12default_hook17hf6fdb8e9192be332E
std::panicking::default_hook
$ rustfilt _ZN3std9panicking12default_hook17hf6fdb8e9192be332E
std::panicking::default_hook
```

**Comment by glandium** [comment]
rustfilt shouldn't strip characters off non-demangled symbols, though.

**Comment by alexcrichton** [comment]
Indeed! That's a bug with rustc-demangle
