### ISSUE TITLE
demangle stderr

### ISSUE THREAD

**Issue by devsnek** [luser/rustfilt#9]
Right now if a program you pipe into rustfilt outputs the symbols in stderr instead of stdout (which is likely, as they're usually part of error output), they will be ignored because rustfilt itself doesn't handle stderr.

Right now I handle this by doing `x 2>&1 | rustfilt` to pipe stderr to stdout in my program runs.

**Comment by luser** [comment]
I don't think it's possible for `rustfilt` to do this itself. Your shell spawns the processes in the pipeline, so it's the thing that makes decisions about what program's output goes where. `rustfilt` can only handle the input streams it's given.

**Comment by devsnek** [comment]
ah you're right, I assumed there was some way it could be added. thanks.
